name: first workflow

on:
  push:
    branches:
      - master

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: print a welcome message
        run: echo "welcome to out first gha workflow"
      
      - name: checkout repository
        uses: actions/checkout@v5.0.0
      
      - name: List repo files
        run: ls -la
        
  
