on: 
    push:
      branches:
        - master
        - "release/**"
      paths:
        - "src/**"
    pull_request:
      branches:
        - master
        - "release/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0
      - name: run tests
        run: npm test